In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
df = pd.read_csv('../data/adri_data/entrenamiento_postulaciones_vistas4.csv', encoding='utf-8')
# df.drop(['idzona', 'idciudad','idmapacalle'], axis=1, inplace=True)
df.shape

(9940108, 41)

In [3]:
mintimestamp = df['timestamp'].min()
df['timestamp'] = df['timestamp']-mintimestamp

In [4]:
mintimestamp = df['idpostulante_int'].min()
df['idpostulante_int'] = df['idpostulante_int']-mintimestamp

In [5]:
cols = df.head(0)
cols.drop(['se_postulo', 'idaviso', 'idpostulante'], inplace=True, axis=1)
cols = cols.columns
cols

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Index(['esta_online', 'titulo_analista', 'titulo_tecnico',
       'titulo_administrativo', 'titulo_vendedor', 'titulo_comercial',
       'titulo_ventas', 'titulo_sr', 'titulo_importante', 'titulo_jefe',
       'titulo_empresa', 'titulo_asistente', 'titulo_supervisor', 'titulo_jr',
       'titulo_contable', 'desc_experiencia', 'desc_empresa', 'desc_trabajo',
       'desc_excluyente', 'desc_manejo', 'desc_importante', 'desc_equipo',
       'desc_tareas', 'desc_cliente', 'desc_clientes', 'desc_conocimientos',
       'idzona', 'idciudad', 'idmapacalle', 'idtipo_de_trabajo',
       'idnivel_laboral', 'idnombre_area', 'iddenominacion_empresa',
       'timestamp', 'valor_educacion', 'sexo', 'edad', 'idpostulante_int'],
      dtype='object')

In [6]:
df.head()

,idaviso,esta_online,titulo_analista,titulo_tecnico,titulo_administrativo,titulo_vendedor,titulo_comercial,titulo_ventas,titulo_sr,titulo_importante,...,idnivel_laboral,idnombre_area,iddenominacion_empresa,idpostulante,timestamp,valor_educacion,sexo,edad,se_postulo,idpostulante_int
0,1112448580,1,0,1,0,0,0,0,0,0,...,5,136,439,rmRqLJA,1710732.612,10.0,2,25,1,419937
1,1112288191,0,0,0,0,0,0,0,0,0,...,3,118,1546,96XeeQ8,8262235.612,-1.0,-1,-1,1,112588
2,1112339031,1,0,0,0,0,0,0,0,0,...,0,24,160,N5lJLJ,6437500.612,11.0,2,30,1,205868
3,1112198634,0,0,0,0,0,0,0,0,0,...,0,116,202,RzrrPbY,6871675.612,12.0,2,27,1,250580
4,1112453169,1,0,0,0,1,0,0,0,0,...,0,182,1131,lDLQ6W8,1683639.612,6.0,1,33,1,378841

In [7]:
# X will have the numeric data, Y will have the target class
dfix = df.loc[:,cols]
X = np.array(dfix)
y = np.array(df['se_postulo'])

In [8]:
# Split into train and test, use only 10% as test (15 flowers)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=7506)
X_test

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        2.10000e+01, 4.40460e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        3.50000e+01, 1.20990e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 2.00000e+00,
        3.50000e+01, 1.79257e+05],
       ...,
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        2.60000e+01, 1.07111e+05],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        3.20000e+01, 2.92883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 2.00000e+00,
        2.70000e+01, 3.39010e+05]])

In [9]:
y_test

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [10]:
for i in range(1, 2):    
    knn = KNeighborsClassifier(n_neighbors=i)                 # Create KNN classifier
    knn.fit(X_train, y_train)                                 # FIT (this does nothing in normal KNN)
    pred = knn.predict(X_test)                                # predict the response
    print (str(i) + ": " + str(accuracy_score(y_test, pred))) # evaluate accuracy

# 1: 0.9169948823503965
# 2: 0.903654989733514
# 3: 0.9077424696507382
# 4: 0.9014487767237989

1: 0.9169948823503965

# Predigo con todos los datos

In [11]:
top100_full = pd.read_csv("../test_final_100k.csv", encoding='utf-8')

In [12]:
# id_postulantes = pd.read_csv('../data/adri_data/entrenamiento_id_postulantes.csv', encoding='utf-8')
# id_postulantes.shape
# id_postulantes.head()

In [13]:
# top100_full = pd.merge(top100, id_postulantes, how='left', on='idpostulante')
# top100_full.shape

In [14]:
# top100_full.rename({'idpostulante':'idpostulante_old'}, inplace=True, axis=1)
# top100_full.rename({'idpostulante2':'idpostulante'}, inplace=True, axis=1)
# top100_full.shape

In [15]:
top100_full.head()

   id  idaviso idpostulante
0   0   739260       6M9ZQR
1   1   739260       6v1xdL
2   2   739260       ezRKm9
3   3   758580       1Q35ej
4   4   758580       EAN4J6

In [16]:
dfix2 = pd.merge(top100_full, df, how='left', on=['idaviso','idpostulante'])
dfix2.shape

(100000, 42)

In [17]:
dfix2

,id,idaviso,idpostulante,esta_online,titulo_analista,titulo_tecnico,titulo_administrativo,titulo_vendedor,titulo_comercial,titulo_ventas,...,idtipo_de_trabajo,idnivel_laboral,idnombre_area,iddenominacion_empresa,timestamp,valor_educacion,sexo,edad,se_postulo,idpostulante_int
0,0,739260,6M9ZQR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,739260,6v1xdL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,739260,ezRKm9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,758580,1Q35ej,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,758580,EAN4J6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,758580,8R6pzR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,776420,aZJ2XN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,776420,Nmpo3J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,776420,eVqWar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,820850,6ZBD33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,820850,1j4RNj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,820850,ZOwE8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,820850,NG4BaD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,914880,6q6eNl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,914880,8E8pWj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,914880,eVqbDr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1112360,6kRZ44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1112360,8XGB3D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1112360,5qVB9X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1112360,Z6zxXZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1141070,edaNB4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1141070,EZ9pe6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1141070,aXa55D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1144960,NEJjvL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1144960,6Q32Vj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1144960,NWxrWL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1145170,Y9d5Bw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1145170,edaoDp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1145170,Z8pvLz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1176260,ZvQJ2z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,99970,1112515048,EbooLJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99971,99971,1112515048,Zv1eoY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99972,99972,1112515048,YqJLDw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99973,99973,1112515056,8RODvz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99974,99974,1112515056,50p1Zp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99975,99975,1112515056,aZJQP9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99976,99976,1112515069,eZ8294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99977,99977,1112515069,NROBQ4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99978,99978,1112515069,a8YdG9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99979,99979,1112515080,8EQpWl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99980,99980,1112515080,ZREM3E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99981,99981,1112515080,NDaAYJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99982,99982,1112515081,EwKNO6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99983,99983,1112515081,aZJWvq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99984,99984,1112515081,8R4ZBz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99985,99985,1112515099,eprYVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99986,99986,1112515099,8E8lLW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99987,99987,1112515099,Z0A84P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99988,99988,1112515103,Y6xQ4q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99989,99989,1112515103,NRO8wz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99990,99990,1112515103,ZvQaaY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99991,99991,1112515105,ZREdK1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99992,99992,1112515105,NmpeRJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99993,99993,1112515105,5RVLZv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99994,99994,1112515111,YqJDoD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99995,99995,1112515111,5RVZBp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99996,99996,1112515111,ZvQXN1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99997,99997,1112515116,NmpwAB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99998,99998,1112515116,aZJMqJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99999,99999,1112515116,8R48Ex,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
dfix3 = dfix2[cols]

In [19]:
dfix3.head()

,esta_online,titulo_analista,titulo_tecnico,titulo_administrativo,titulo_vendedor,titulo_comercial,titulo_ventas,titulo_sr,titulo_importante,titulo_jefe,...,idmapacalle,idtipo_de_trabajo,idnivel_laboral,idnombre_area,iddenominacion_empresa,timestamp,valor_educacion,sexo,edad,idpostulante_int
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
dfix3.fillna(0, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3035: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [21]:
X_full_data = np.array(dfix3)
X_full_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
pred_full_data = knn.predict(X_full_data)

In [23]:
dfix2['sepostulo'] = pred_full_data

In [24]:
dfix2 = dfix2[['id', 'idaviso', 'idpostulante', 'se_postulo', 'sepostulo']]

In [25]:
# dfix2.drop(['valor_educacion', 'timestamp', 'sexo','edad','idtitulo','idzona','idciudad','idmapacalle',
#             'idtipo_de_trabajo','idnivel_laboral','idnombre_area','iddenominacion_empresa'], inplace=True, axis=1)
dfix2[dfix2['se_postulo'].isnull()].shape

(60066, 5)

In [26]:
dfix2[dfix2['id'] == 594]

      id   idaviso idpostulante  se_postulo  sepostulo
594  594  17903700      Yj5q3xX         1.0          1

In [27]:
dfix2.fillna(0, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3035: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [28]:
top100_full = dfix2[['id', 'se_postulo', 'sepostulo']]
top100_full.head()

   id  se_postulo  sepostulo
0   0         0.0          0
1   1         0.0          0
2   2         0.0          0
3   3         0.0          0
4   4         0.0          0

In [29]:
top100_full['se_postulo'] = top100_full['se_postulo'].astype('int')
top100_full['sepostulo'] = top100_full['sepostulo'].astype('int')
top100_full.shape

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

(100000, 3)

In [30]:
top100_full.loc[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1), 'sepostulo'] = 1
top100_full[(top100_full['sepostulo'] == 0) & (top100_full['se_postulo'] == 1)]['sepostulo']

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

Series([], Name: sepostulo, dtype: int32)

In [31]:
top100_full.drop('se_postulo', axis=1, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
top100_full[top100_full['sepostulo'] == 1].shape

(34595, 2)

In [33]:
top100_full.to_csv('../data/adri_data/top100k.csv', encoding='utf-8', index=False)

KeyError: 'idaviso'